name: test

on:
  push

jobs:
  curl_test:
    runs-on: ubuntu-latest 
    steps:
    - name: test
      run: |
        echo ${{ vars.TEST_URL }}
        echo "$env:URL"
        curl -c 5 ${{ vars.TEST_URL }}
