name: test

on: 
  pull_request:
    types: 
      - edited

jobs:
  curl_test:
    runs-on: ubuntu-latest 
    steps:
    - name: test
      run: |
        branch=$(echo feature/a/a | sed -e 's/\//\-/g')
        echo ${branch}
        echo ${{ vars.TEST_URL }}
        echo ${{vars.TEST_URL}}
        echo ${{secrets.SC_URL}}
        echo "aaa"
