name: test

on:
  push

jobs:
  curl_test:
    runs-on: ubuntu-latest 
    steps:
    - name: test
      env:
        URL: ${{ secrets.TEST_URL }}
      run: |
        echo "URL"
        echo "$env:URL"
        curl ${{ secrets.TEST_URL }}
