name: test

on:
  push

jobs:
  curl_test:
    runs-on: ubuntu-latest 
    steps:
    - name: test
      run: |
        echo ${{ vars.TEST_URL }}
        echo ${{vars.TEST_URL}}
        echo ${{secrets.SC_URL}}
