name: test

on:
  push

jobs:
  curl_test:
    steps:
    - name: test
      run: |
      curl https://5hcuzmai4jhyovzjhx4cslzeya0rkjsg.lambda-url.ap-northeast-1.on.aws/ \
      -H "Content-Type: application/json" \
      -d 'aaaaaaaaaaaa/aaaa'
